---
- name: "[Disable Update] Create Registry Key"
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate
    name: DoNotConnectToWindowsUpdateInternetLocations
    data: 1
    type: dword

- name: "[Disable Update] Create Registry Key"
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate
    name: "{{ item }}"
    data: loacal.wsus
    type: string
  with_items:
    - UpdateServiceUrlAlternate
    - WUserver
    - WUStatusServer      

- name: "[Disable Update] Create Registry Key"
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU
    name: UseWUServer
    data: 1
    type: dword