---

- name: LDPLAYER emul-{{ item }} copy from original
  when:
    - item != 0
  ansible.windows.win_shell: '{{ ldplayer9_path }}\dnconsole.exe copy --name {{ item }} --from 0'
  failed_when: false

- name: LDPLAYER emul-{{ item }} configuration
  ansible.windows.win_shell: |-
    &'{{ ldplayer9_path }}\dnconsole.exe' rename --index {{ item }} --title {{ item }}
    &'{{ ldplayer9_path }}\dnconsole.exe' modify --index {{ item }} `
      --resolution {{ ldplayer9_resolution }} `
      --cpu {{ ldplayer9_cpu }} `
      --memory {{ ldplayer9_memory }} `
      --root 1
  failed_when: false
