---

- name: LDPLAYER  Disable updates
  when: ldplayer9_disable_updates is defined and ldplayer9_disable_updates | bool
  community.windows.win_lineinfile:
    path: C:\Windows\System32\drivers\etc\hosts
    line: 0.0.0.0 {{ item }}
  loop:
    - apien.ldmnq.com
    - encdn.ldmnq.com

- name: LDPLAYER Disable adverrtisment
  ansible.windows.win_copy:
    src: data.ini
    dest: "{{ ldplayer9_path }}\\data"
    force: true

- name: LDPLAYER Get current global config
  ansible.builtin.slurp:
    src: '{{ ldplayer9_path }}\vms\config\leidians.config'
  register: leidians_config

- name: LDPLAYER Apply global config
  ansible.windows.win_copy:
    content: '{{ global_config | default("[]", true) | combine(template_config) | to_nice_json }}'
    dest: '{{ ldplayer9_path }}\vms\config\leidians.config'
  vars:
    template_config: '{{ lookup("template", "leidians.config") }}'
    global_config: '{{ leidians_config.content | b64decode | from_json }}'

- name: LDPLAYER set name and configuration for emu 0
  ansible.windows.win_shell: |-
    &'{{ ldplayer9_path }}\dnconsole.exe' rename --index 0 --title origin
    &'{{ ldplayer9_path }}\dnconsole.exe' modify --index 0 `
      --resolution {{ ldplayer9_resolution }} `
      --cpu {{ ldplayer9_cpu }} `
      --memory {{ ldplayer9_memory }}
  failed_when: false

- name: Get config content for emu 0
  ansible.builtin.slurp:
    src: '{{ ldplayer9_path }}\vms\config\leidian0.config'
  register: current_emu_config

- name: Apply root mode and adb debug
  ansible.windows.win_copy:
    content: '{{ emu_config | default("[]", true) | combine(basic_config) | to_nice_json }}'
    dest: '{{ ldplayer9_path }}\vms\config\leidian0.config'
  vars:
    basic_config: '{{ lookup("template", "basic_settings.json") }}'
    emu_config: '{{ current_emu_config.content | b64decode | from_json }}'
