---

- hosts: '{{ target | default("localhost") }}'
  gather_facts: true
  roles:
    #  - { role: 'roles/openssh',                     tags: ['openssh'] }
     - { role: 'roles/win_common_setup',            tags: ['win_common_setup'] }
     - { role: 'roles/dependencies',                tags: ['dependencies'] }
